[2023-10-10T15:32:10.390+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: airflow_exam.compute_dt_score scheduled__2023-10-10T15:31:00+00:00 [queued]>
[2023-10-10T15:32:10.432+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: airflow_exam.compute_dt_score scheduled__2023-10-10T15:31:00+00:00 [queued]>
[2023-10-10T15:32:10.435+0000] {taskinstance.py:1359} INFO - Starting attempt 1 of 1
[2023-10-10T15:32:10.459+0000] {taskinstance.py:1380} INFO - Executing <Task(PythonOperator): compute_dt_score> on 2023-10-10 15:31:00+00:00
[2023-10-10T15:32:10.495+0000] {standard_task_runner.py:57} INFO - Started process 3229 to run task
[2023-10-10T15:32:10.521+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', '***_exam', 'compute_dt_score', 'scheduled__2023-10-10T15:31:00+00:00', '--job-id', '162', '--raw', '--subdir', 'DAGS_FOLDER/DAG.py', '--cfg-path', '/tmp/tmp_ozfykwf']
[2023-10-10T15:32:10.524+0000] {standard_task_runner.py:85} INFO - Job 162: Subtask compute_dt_score
[2023-10-10T15:32:10.546+0000] {warnings.py:109} WARNING - /home/***/.local/lib/python3.8/site-packages/***/settings.py:195: DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
  SQL_ALCHEMY_CONN = conf.get("database", "SQL_ALCHEMY_CONN")

[2023-10-10T15:32:10.657+0000] {task_command.py:415} INFO - Running <TaskInstance: airflow_exam.compute_dt_score scheduled__2023-10-10T15:31:00+00:00 [running]> on host 137abce082a9
[2023-10-10T15:32:10.814+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='***_exam' AIRFLOW_CTX_TASK_ID='compute_dt_score' AIRFLOW_CTX_EXECUTION_DATE='2023-10-10T15:31:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-10-10T15:31:00+00:00'
[2023-10-10T15:32:10.830+0000] {taskinstance.py:1935} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 192, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 209, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/Load_ml.py", line 81, in compute_dt_score
    X, y = prepare_data()
  File "/opt/airflow/dags/Load_ml.py", line 32, in prepare_data
    df = pd.read_csv(path_to_data)
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/io/parsers/readers.py", line 912, in read_csv
    return _read(filepath_or_buffer, kwds)
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/io/parsers/readers.py", line 577, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/io/parsers/readers.py", line 1407, in __init__
    self._engine = self._make_engine(f, self.engine)
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/io/parsers/readers.py", line 1661, in _make_engine
    self.handles = get_handle(
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/io/common.py", line 859, in get_handle
    handle = open(
FileNotFoundError: [Errno 2] No such file or directory: 'app/clean_data/data.csv'
[2023-10-10T15:32:10.852+0000] {taskinstance.py:1398} INFO - Marking task as FAILED. dag_id=***_exam, task_id=compute_dt_score, execution_date=20231010T153100, start_date=20231010T153210, end_date=20231010T153210
[2023-10-10T15:32:10.877+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 162 for task compute_dt_score ([Errno 2] No such file or directory: 'app/clean_data/data.csv'; 3229)
[2023-10-10T15:32:10.893+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2023-10-10T15:32:10.949+0000] {taskinstance.py:2776} INFO - 0 downstream tasks scheduled from follow-on schedule check
